# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tk-MinMaxScale
version:      0.09
version_from: MinMaxScale.pm
installdirs:  site
requires:
    Tk:                            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
